# Generated by Django 4.2 on 2023-04-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='created_by',
            field=models.IntegerField(default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payments',
            name='created_by',
            field=models.IntegerField(default=1, max_length=4),
            preserve_default=False,
        ),
    ]
