# Generated by Django 4.2 on 2023-04-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_categories_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='created_by',
        ),
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
