# Generated by Django 4.2 on 2023-04-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_remove_payments_created_by_product_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='wallet',
            field=models.IntegerField(default=0),
        ),
    ]
