# Generated by Django 4.2 on 2023-04-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_registration_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='paid_to',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
